# Generated by Django 4.2.8 on 2023-12-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Name', models.TextField(max_length=200)),
                ('Type', models.DateTimeField(auto_now_add=True)),
                ('Finished_Date', models.DateTimeField()),
                ('Keyword', models.CharField(max_length=200)),
            ],
        ),
    ]
