# Generated by Django 4.2.8 on 2023-12-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Keyword',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='Name',
            field=models.TextField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='Type',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
