# Generated by Django 4.2.8 on 2023-12-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_case_keyword_alter_case_name_alter_case_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Type',
            field=models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('type3', 'Type 3')], db_index=True, default='type1', max_length=20),
        ),
    ]
